version: "3.8"
services:
  worker:
    build: 
      context : ./learningmachines
      dockerfile : ./learningmachines/Dockerfile
  uwsgi:
    build:
      context: ./learningmachines
      dockerfile : ./searcher/Dockerfile
    expose:
      - 8001
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - uwsgi
